export default [
	{
		"Set": "Dominion (Second Edition)",
		"Card Name": "Harbinger",
		"Cost": 3,
		"Type": "Action",
		"Tags": "+1 Card,+1 Action",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/3/32/Harbinger.jpg/200px-Harbinger.jpg",
	},
	{
		"Set": "Dominion (Second Edition)",
		"Card Name": "Merchant",
		"Cost": 3,
		"Type": "Action",
		"Tags": "+1 Card,+1 Action",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/7/78/Merchant.jpg/200px-Merchant.jpg",
	},
	{
		"Set": "Dominion (Second Edition)",
		"Card Name": "Vassal",
		"Cost": 3,
		"Type": "Action",
		"Tags": "+ Coins",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/0/0b/Vassal.jpg/200px-Vassal.jpg",
	},
	{
		"Set": "Dominion (Second Edition)",
		"Card Name": "Poacher",
		"Cost": 4,
		"Type": "Action",
		"Tags": "+1 Card,+1 Action,+ Coins",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/a/a0/Poacher.jpg/200px-Poacher.jpg",
	},
	{
		"Set": "Dominion (Second Edition)",
		"Card Name": "Bandit",
		"Cost": 5,
		"Type": "Action,Attack",
		"Tags": "Gain Card(s),Trash,Aggressive",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/4/46/Bandit.jpg/200px-Bandit.jpg",
	},
	{
		"Set": "Dominion (Second Edition)",
		"Card Name": "Sentry",
		"Cost": 5,
		"Type": "Action",
		"Tags": "+1 Card,+1 Action",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/4/4c/Sentry.jpg/200px-Sentry.jpg",
	},
	{
		"Set": "Dominion (Second Edition)",
		"Card Name": "Artisan",
		"Cost": 6,
		"Type": "Action",
		"Tags": "Gain Card(s)",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/1/1d/Artisan.jpg/200px-Artisan.jpg",
	},
	{
		"Set": "Dominion (First Edition)",
		"Card Name": "Chancellor",
		"Cost": 3,
		"Type": "Action",
		"Tags": "+ Coins",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/b/b7/Chancellor.jpg/200px-Chancellor.jpg",
	},
	{
		"Set": "Dominion (First Edition)",
		"Card Name": "Woodcutter",
		"Cost": 3,
		"Type": "Action",
		"Tags": "+ Coins,+ Buy",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/d/d6/Woodcutter.jpg/200px-Woodcutter.jpg",
	},
	{
		"Set": "Dominion (First Edition)",
		"Card Name": "Feast",
		"Cost": 4,
		"Type": "Action",
		"Tags": "Trash,Gain Card(s)",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/9/9c/Feast.jpg/200px-Feast.jpg",
	},
	{
		"Set": "Dominion (First Edition)",
		"Card Name": "Spy",
		"Cost": 4,
		"Type": "Action,Attack",
		"Tags": "+1 Card,+1 Action,Aggressive",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/c/cb/Spy.jpg/200px-Spy.jpg",
	},
	{
		"Set": "Dominion (First Edition)",
		"Card Name": "Thief",
		"Cost": 4,
		"Type": "Action,Attack",
		"Tags": "Aggressive,Trash,Gain Card(s)",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/f/f5/Thief.jpg/200px-Thief.jpg",
	},
	{
		"Set": "Dominion (First Edition)",
		"Card Name": "Adventurer",
		"Cost": 6,
		"Type": "Action",
		"Tags": "+ Multiple Cards,Cycle",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/7/71/Adventurer.jpg/200px-Adventurer.jpg",
	},
	{
		"Set": "Dominion (First Edition),Dominion (Second Edition)",
		"Card Name": "Cellar",
		"Cost": 2,
		"Type": "Action",
		"Tags": "+1 Action,Cycle",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/1/1c/Cellar.jpg/200px-Cellar.jpg",
	},
	{
		"Set": "Dominion (First Edition),Dominion (Second Edition)",
		"Card Name": "Chapel",
		"Cost": 2,
		"Type": "Action",
		"Tags": "Trash",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/2/29/Chapel.jpg/200px-Chapel.jpg",
	},
	{
		"Set": "Dominion (First Edition),Dominion (Second Edition)",
		"Card Name": "Moat",
		"Cost": 2,
		"Type": "Action,Reaction",
		"Tags": "+ Multiple Cards,Reaction to Attacks",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/f/fe/Moat.jpg/200px-Moat.jpg",
	},
	{
		"Set": "Dominion (First Edition),Dominion (Second Edition)",
		"Card Name": "Village",
		"Cost": 3,
		"Type": "Action",
		"Tags": "+1 Card,+ Multiple Actions",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/5/5a/Village.jpg/200px-Village.jpg",
	},
	{
		"Set": "Dominion (First Edition),Dominion (Second Edition)",
		"Card Name": "Workshop",
		"Cost": 3,
		"Type": "Action",
		"Tags": "Gain Card(s)",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/5/50/Workshop.jpg/200px-Workshop.jpg",
	},
	{
		"Set": "Dominion (First Edition),Dominion (Second Edition)",
		"Card Name": "Bureaucrat",
		"Cost": 4,
		"Type": "Action,Attack",
		"Tags": "Aggressive",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/4/4d/Bureaucrat.jpg/200px-Bureaucrat.jpg",
	},
	{
		"Set": "Dominion (First Edition),Dominion (Second Edition)",
		"Card Name": "Gardens",
		"Cost": 4,
		"Type": "Victory",
		"Tags": [],
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/8/8c/Gardens.jpg/200px-Gardens.jpg",
	},
	{
		"Set": "Dominion (First Edition),Dominion (Second Edition)",
		"Card Name": "Militia",
		"Cost": 4,
		"Type": "Action,Attack",
		"Tags": "Aggressive",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/a/a0/Militia.jpg/200px-Militia.jpg",
	},
	{
		"Set": "Dominion (First Edition),Dominion (Second Edition)",
		"Card Name": "Moneylender",
		"Cost": 4,
		"Type": "Action",
		"Tags": "+ Coins,Trash",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/7/70/Moneylender.jpg/200px-Moneylender.jpg",
	},
	{
		"Set": "Dominion (First Edition),Dominion (Second Edition)",
		"Card Name": "Remodel",
		"Cost": 4,
		"Type": "Action",
		"Tags": "Upgrade,Trash",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/2/2e/Remodel.jpg/200px-Remodel.jpg",
	},
	{
		"Set": "Dominion (First Edition),Dominion (Second Edition)",
		"Card Name": "Smithy",
		"Cost": 4,
		"Type": "Action",
		"Tags": "+ Multiple Cards",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/3/36/Smithy.jpg/200px-Smithy.jpg",
	},
	{
		"Set": "Dominion (First Edition),Dominion (Second Edition)",
		"Card Name": "Throne Room",
		"Cost": 4,
		"Type": "Action",
		"Tags": [],
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/d/d1/Throne Room.jpg/200px-Throne Room.jpg",
	},
	{
		"Set": "Dominion (First Edition),Dominion (Second Edition)",
		"Card Name": "Council Room",
		"Cost": 5,
		"Type": "Action",
		"Tags": "+ Multiple Cards",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/e/e0/Council Room.jpg/200px-Council Room.jpg",
	},
	{
		"Set": "Dominion (First Edition),Dominion (Second Edition)",
		"Card Name": "Festival",
		"Cost": 5,
		"Type": "Action",
		"Tags": "+ Multiple Actions,+ Coins,+ Buy",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/e/ec/Festival.jpg/200px-Festival.jpg",
	},
	{
		"Set": "Dominion (First Edition),Dominion (Second Edition)",
		"Card Name": "Laboratory",
		"Cost": 5,
		"Type": "Action",
		"Tags": "+ Multiple Cards,+1 Action",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/0/0c/Laboratory.jpg/200px-Laboratory.jpg",
	},
	{
		"Set": "Dominion (First Edition),Dominion (Second Edition)",
		"Card Name": "Library",
		"Cost": 5,
		"Type": "Action",
		"Tags": "Cycle",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/9/98/Library.jpg/200px-Library.jpg",
	},
	{
		"Set": "Dominion (First Edition),Dominion (Second Edition)",
		"Card Name": "Market",
		"Cost": 5,
		"Type": "Action",
		"Tags": "+1 Card,+1 Action,+ Buy,+ Coins",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/7/7e/Market.jpg/200px-Market.jpg",
	},
	{
		"Set": "Dominion (First Edition),Dominion (Second Edition)",
		"Card Name": "Mine",
		"Cost": 5,
		"Type": "Action",
		"Tags": "Upgrade,Trash",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/8/8e/Mine.jpg/200px-Mine.jpg",
	},
	{
		"Set": "Dominion (First Edition),Dominion (Second Edition)",
		"Card Name": "Witch",
		"Cost": 5,
		"Type": "Action,Attack",
		"Tags": "+ Multiple Cards,Curse",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/f/f3/Witch.jpg/200px-Witch.jpg",
	},
	{
		"Set": "Intrigue (First Edition)",
		"Card Name": "Secret Chamber",
		"Cost": 2,
		"Type": "Action,Reaction",
		"Tags": "+ Coins,Reaction to Attacks,Cycle",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/b/b3/Secret Chamber.jpg/200px-Secret Chamber.jpg",
	},
	{
		"Set": "Intrigue (First Edition)",
		"Card Name": "Great Hall",
		"Cost": 3,
		"Type": "Victory,Action",
		"Tags": "+1 Card,+1 Action,Victory",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/9/95/Great Hall.jpg/200px-Great Hall.jpg",
	},
	{
		"Set": "Intrigue (First Edition)",
		"Card Name": "Coppersmith",
		"Cost": 4,
		"Type": "Action",
		"Tags": "+ Coins",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/4/40/Coppersmith.jpg/200px-Coppersmith.jpg",
	},
	{
		"Set": "Intrigue (First Edition)",
		"Card Name": "Scout",
		"Cost": 4,
		"Type": "Action",
		"Tags": "+1 Action,+ Multiple Cards",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/4/46/Scout.jpg/200px-Scout.jpg",
	},
	{
		"Set": "Intrigue (First Edition)",
		"Card Name": "Saboteur",
		"Cost": 5,
		"Type": "Action,Attack",
		"Tags": "Aggressive,Trash,Gain Card(s)",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/6/60/Saboteur.jpg/200px-Saboteur.jpg",
	},
	{
		"Set": "Intrigue (First Edition)",
		"Card Name": "Tribute",
		"Cost": 5,
		"Type": "Action",
		"Tags": " Aggressive,+ Multiple Actions,+ Coins,+ Multiple Cards",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/0/00/Tribute.jpg/200px-Tribute.jpg",
	},
	{
		"Set": "Intrigue (Second Edition)",
		"Card Name": "Lurker",
		"Cost": 2,
		"Type": "Action",
		"Tags": "Trash,+1 Action",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/f/f7/Lurker.jpg/200px-Lurker.jpg",
	},
	{
		"Set": "Intrigue (Second Edition)",
		"Card Name": "Diplomat",
		"Cost": 4,
		"Type": "Action,Reaction",
		"Tags": "+ Multiple Cards,+ Multiple Actions,Reaction to Attacks",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/8/85/Diplomat.jpg/200px-Diplomat.jpg",
	},
	{
		"Set": "Intrigue (Second Edition)",
		"Card Name": "Mill",
		"Cost": 4,
		"Type": "Victory,Action",
		"Tags": "+1 Card,+1 Action,+ Coins",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/1/10/Mill.jpg/200px-Mill.jpg",
	},
	{
		"Set": "Intrigue (Second Edition)",
		"Card Name": "Secret Passage",
		"Cost": 4,
		"Type": "Action",
		"Tags": "+ Multiple Cards,+1 Action",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/b/b4/Secret Passage.jpg/200px-Secret Passage.jpg",
	},
	{
		"Set": "Intrigue (Second Edition)",
		"Card Name": "Courtier",
		"Cost": 5,
		"Type": "Action",
		"Tags": "+1 Action,+ Buy,+ Coins,Gain Card(s)",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/7/7c/Courtier.jpg/200px-Courtier.jpg",
	},
	{
		"Set": "Intrigue (Second Edition)",
		"Card Name": "Patrol",
		"Cost": 5,
		"Type": "Action",
		"Tags": "+ Multiple Cards",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/c/c8/Patrol.jpg/200px-Patrol.jpg",
	},
	{
		"Set": "Intrigue (Second Edition)",
		"Card Name": "Replace",
		"Cost": 5,
		"Type": "Action,Attack",
		"Tags": "Trash,Curse,Upgrade,Aggressive",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/2/27/Replace.jpg/200px-Replace.jpg",
	},
	{
		"Set": "Intrigue (First Edition),Intrigue (Second Edition)",
		"Card Name": "Courtyard",
		"Cost": 2,
		"Type": "Action",
		"Tags": "+ Multiple Cards",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/3/30/Courtyard.jpg/200px-Courtyard.jpg",
	},
	{
		"Set": "Intrigue (First Edition),Intrigue (Second Edition)",
		"Card Name": "Pawn",
		"Cost": 2,
		"Type": "Action",
		"Tags": "+1 Card,+1 Action,+ Buy,+ Coins",
		"Image Address": "http://wiki.dominionstrategy.com/index.php/Pawn",
	},
	{
		"Set": "Intrigue (First Edition),Intrigue (Second Edition)",
		"Card Name": "Masquerade",
		"Cost": 3,
		"Type": "Action",
		"Tags": "+ Multiple Cards, Aggressive,Trash",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/0/0e/Masquerade.jpg/200px-Masquerade.jpg",
	},
	{
		"Set": "Intrigue (First Edition),Intrigue (Second Edition)",
		"Card Name": "Shanty Town",
		"Cost": 3,
		"Type": "Action",
		"Tags": "+ Multiple Actions,+ Multiple Cards",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/8/8e/Shanty Town.jpg/200px-Shanty Town.jpg",
	},
	{
		"Set": "Intrigue (First Edition),Intrigue (Second Edition)",
		"Card Name": "Steward",
		"Cost": 3,
		"Type": "Action",
		"Tags": "+ Multiple Cards,+ Coins,Trash",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/8/88/Steward.jpg/200px-Steward.jpg",
	},
	{
		"Set": "Intrigue (First Edition),Intrigue (Second Edition)",
		"Card Name": "Swindler",
		"Cost": 3,
		"Type": "Action,Attack",
		"Tags": "+ Coins,Aggressive,Trash",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/e/e7/Swindler.jpg/200px-Swindler.jpg",
	},
	{
		"Set": "Intrigue (First Edition),Intrigue (Second Edition)",
		"Card Name": "Wishing Well",
		"Cost": 3,
		"Type": "Action",
		"Tags": "+1 Card,+1 Action",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/f/f7/Wishing Well.jpg/200px-Wishing Well.jpg",
	},
	{
		"Set": "Intrigue (First Edition),Intrigue (Second Edition)",
		"Card Name": "Baron",
		"Cost": 4,
		"Type": "Action",
		"Tags": "+ Buy,+ Coins",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/7/73/Baron.jpg/200px-Baron.jpg",
	},
	{
		"Set": "Intrigue (First Edition),Intrigue (Second Edition)",
		"Card Name": "Bridge",
		"Cost": 4,
		"Type": "Action",
		"Tags": "+ Buy,+ Coins",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/3/39/Bridge.jpg/200px-Bridge.jpg",
	},
	{
		"Set": "Intrigue (First Edition),Intrigue (Second Edition)",
		"Card Name": "Conspirator",
		"Cost": 4,
		"Type": "Action",
		"Tags": "+ Coins,+1 Card,+1 Action",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/4/42/Conspirator.jpg/200px-Conspirator.jpg",
	},
	{
		"Set": "Intrigue (First Edition),Intrigue (Second Edition)",
		"Card Name": "Ironworks",
		"Cost": 4,
		"Type": "Action",
		"Tags": "Gain Card(s),+1 Action,+ Coins,+1 Card",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/7/76/Ironworks.jpg/200px-Ironworks.jpg",
	},
	{
		"Set": "Intrigue (First Edition),Intrigue (Second Edition)",
		"Card Name": "Mining Village",
		"Cost": 4,
		"Type": "Action",
		"Tags": "+1 Card,+ Multiple Actions,+ Coins",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/7/7f/Mining Village.jpg/200px-Mining Village.jpg",
	},
	{
		"Set": "Intrigue (First Edition),Intrigue (Second Edition)",
		"Card Name": "Duke",
		"Cost": 5,
		"Type": "Victory",
		"Tags": [],
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/1/10/Duke.jpg/200px-Duke.jpg",
	},
	{
		"Set": "Intrigue (First Edition),Intrigue (Second Edition)",
		"Card Name": "Minion",
		"Cost": 5,
		"Type": "Action,Attack",
		"Tags": "+1 Action,+ Coins,Cycle,Aggressive",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/4/47/Minion.jpg/200px-Minion.jpg",
	},
	{
		"Set": "Intrigue (First Edition),Intrigue (Second Edition)",
		"Card Name": "Torturer",
		"Cost": 5,
		"Type": "Action,Attack",
		"Tags": "+ Multiple Cards,Aggressive,Curse",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/a/a9/Torturer.jpg/200px-Torturer.jpg",
	},
	{
		"Set": "Intrigue (First Edition),Intrigue (Second Edition)",
		"Card Name": "Trading Post",
		"Cost": 5,
		"Type": "Action",
		"Tags": "Trash,Gain Card(s)",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/3/36/Trading Post.jpg/200px-Trading Post.jpg",
	},
	{
		"Set": "Intrigue (First Edition),Intrigue (Second Edition)",
		"Card Name": "Upgrade",
		"Cost": 5,
		"Type": "Action",
		"Tags": "+1 Card,+1 Action,Trash,Upgrade",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/d/d3/Upgrade.jpg/200px-Upgrade.jpg",
	},
	{
		"Set": "Intrigue (First Edition),Intrigue (Second Edition)",
		"Card Name": "Harem",
		"Cost": 6,
		"Type": "Victory,Treasure",
		"Tags": [],
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/9/9d/Harem.jpg/200px-Harem.jpg",
	},
	{
		"Set": "Intrigue (First Edition),Intrigue (Second Edition)",
		"Card Name": "Nobles",
		"Cost": 6,
		"Type": "Victory,Action",
		"Tags": "+ Multiple Cards,+ Multiple Actions,Victory",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/b/b6/Nobles.jpg/200px-Nobles.jpg",
	},
	{
		"Set": "Alchemy",
		"Card Name": "Herbalist",
		"Cost": 2,
		"Type": "Action",
		"Tags": "+ Buy,+ Coins",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/2/26/Herbalist.jpg/200px-Herbalist.jpg",
	},
	{
		"Set": "Alchemy",
		"Card Name": "Apprentice",
		"Cost": 5,
		"Type": "Action",
		"Tags": "+1 Action,Trash,Gain Card(s)",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/2/20/Apprentice.jpg/200px-Apprentice.jpg",
	},
	{
		"Set": "Alchemy",
		"Card Name": "Transmute",
		"Cost": "Potion",
		"Type": "Action",
		"Tags": "Trash,Gain Card(s),Potion",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/2/22/Transmute.jpg/200px-Transmute.jpg",
	},
	{
		"Set": "Alchemy",
		"Card Name": "Vineyard",
		"Cost": "Potion",
		"Type": "Victory",
		"Tags": "Count Cards,Potion",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/c/c8/Vineyard.jpg/200px-Vineyard.jpg",
	},
	{
		"Set": "Alchemy",
		"Card Name": "Apothecary",
		"Cost": "2,Potion",
		"Type": "Action",
		"Tags": "+1 Card,+1 Action,Potion",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/6/69/Apothecary.jpg/200px-Apothecary.jpg",
	},
	{
		"Set": "Alchemy",
		"Card Name": "Scrying Pool",
		"Cost": "2,Potion",
		"Type": "Action,Attack",
		"Tags": "+1 Action,Aggressive,Gain Card(s),Potion",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/7/79/Scrying_Pool.jpg/200px-Scrying_Pool.jpg",
	},
	{
		"Set": "Alchemy",
		"Card Name": "University",
		"Cost": "2,Potion",
		"Type": "Action",
		"Tags": "+ Multiple Actions,Gain Card(s),Potion",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/9/9b/University.jpg/200px-University.jpg",
	},
	{
		"Set": "Alchemy",
		"Card Name": "Alchemist",
		"Cost": "3,Potion",
		"Type": "Action",
		"Tags": "+ Multiple Cards,+1 Action,Potion",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/2/22/Alchemist.jpg/200px-Alchemist.jpg",
	},
	{
		"Set": "Alchemy",
		"Card Name": "Familiar",
		"Cost": "3,Potion",
		"Type": "Action,Attack",
		"Tags": "+1 Card,+1 Action,Curse,Aggressive,Potion",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/4/48/Familiar.jpg/200px-Familiar.jpg",
	},
	{
		"Set": "Alchemy",
		"Card Name": "Philosophers Stone",
		"Cost": "3,Potion",
		"Type": "Treasure",
		"Tags": "Potion",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/3/32/Philosopher%27s_Stone.jpg/200px-Philosopher%27s_Stone.jpg",
	},
	{
		"Set": "Alchemy",
		"Card Name": "Golem",
		"Cost": "4,Potion",
		"Type": "Action",
		"Tags": "Cycle,Action,Potion",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/d/dc/Golem.jpg/200px-Golem.jpg",
	},
	{
		"Set": "Alchemy",
		"Card Name": "Possession",
		"Cost": "6,Potion",
		"Type": "Action",
		"Tags": "Aggressive,Potion",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/3/3b/Possession.jpg/200px-Possession.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Loan",
		"Cost": 3,
		"Type": "Treasure",
		"Tags": "Cycle",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/1/11/Loan.jpg/200px-Loan.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Trade Route",
		"Cost": 3,
		"Type": "Action",
		"Tags": "+ Buy,Trash,+ Coins",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/a/a7/Trade_Route.jpg/200px-Trade_Route.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Watchtower",
		"Cost": 3,
		"Type": "Action,Reaction",
		"Tags": "Reaction to Attacks,+ Multiple Cards,Trash",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/c/c2/Watchtower.jpg/200px-Watchtower.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Bishop",
		"Cost": 4,
		"Type": "Action",
		"Tags": "+ Coins,Victory Token(s),Trash,Aggressive",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/b/b4/Bishop.jpg/200px-Bishop.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Monument",
		"Cost": 4,
		"Type": "Action",
		"Tags": "+ Coins,Victory Token(s)",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/a/ad/Monument.jpg/200px-Monument.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Quarry",
		"Cost": 4,
		"Type": "Treasure",
		"Tags": [],
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/6/65/Quarry.jpg/200px-Quarry.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Talisman",
		"Cost": 4,
		"Type": "Treasure",
		"Tags": "Gain Card(s)",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/c/cf/Talisman.jpg/200px-Talisman.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Workers Village",
		"Cost": 4,
		"Type": "Action",
		"Tags": "+1 Card,+ Multiple Actions,+ Buy",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/1/12/Worker%27s_Village.jpg/200px-Worker%27s_Village.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "City",
		"Cost": 5,
		"Type": "Action",
		"Tags": "+1 Card,+ Multiple Actions,+ Buy,+ Coins",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/3/30/City.jpg/200px-City.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Contraband",
		"Cost": 5,
		"Type": "Treasure",
		"Tags": "+ Buy",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/5/58/Contraband.jpg/200px-Contraband.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Counting House",
		"Cost": 5,
		"Type": "Action",
		"Tags": "+ Multiple Cards",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/5/5d/Counting_House.jpg/200px-Counting_House.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Mint",
		"Cost": 5,
		"Type": "Action",
		"Tags": "Gain Card(s),Trash",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/b/bc/Mint.jpg/200px-Mint.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Mountebank",
		"Cost": 5,
		"Type": "Action,Attack",
		"Tags": "+ Coins,Curse,Aggressive",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/8/89/Mountebank.jpg/200px-Mountebank.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Rabble",
		"Cost": 5,
		"Type": "Action,Attack",
		"Tags": "+ Multiple Cards,Aggressive",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/f/f1/Rabble.jpg/200px-Rabble.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Royal Seal",
		"Cost": 5,
		"Type": "Treasure",
		"Tags": [],
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/d/dd/Royal_Seal.jpg/200px-Royal_Seal.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Vault",
		"Cost": 5,
		"Type": "Action",
		"Tags": "+ Multiple Cards,+ Coins",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/6/62/Vault.jpg/200px-Vault.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Venture",
		"Cost": 5,
		"Type": "Treasure",
		"Tags": "Cycle",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/6/62/Vault.jpg/200px-Vault.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Goons",
		"Cost": 6,
		"Type": "Action,Attack",
		"Tags": "+ Buy,+ Coins,Aggressive,Victory Token(s)",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/e/e2/Goons.jpg/200px-Goons.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Grand Market",
		"Cost": 6,
		"Type": "Action",
		"Tags": "+1 Card,+1 Action,+ Buy,+ Coins",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/8/81/Grand_Market.jpg/200px-Grand_Market.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Hoard",
		"Cost": 6,
		"Type": "Treasure",
		"Tags": "Gain Card(s)",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/d/d1/Hoard.jpg/200px-Hoard.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Bank",
		"Cost": 7,
		"Type": "Treasure",
		"Tags": [],
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/7/78/Bank.jpg/200px-Bank.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Expand",
		"Cost": 7,
		"Type": "Action",
		"Tags": "Trash,Upgrade",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/d/dc/Expand.jpg/200px-Expand.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Forge",
		"Cost": 7,
		"Type": "Action",
		"Tags": "Trash,Gain Card(s)",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/d/d7/Forge.jpg/200px-Forge.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Kings Court",
		"Cost": 7,
		"Type": "Action",
		"Tags": [],
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/8/8d/King%27s_Court.jpg/200px-King%27s_Court.jpg",
	},
	{
		"Set": "Prosperity",
		"Card Name": "Peddler",
		"Cost": 8,
		"Type": "Action",
		"Tags": "+1 Card,+1 Action,+ Coins",
		"Image Address": "http://wiki.dominionstrategy.com/images/thumb/6/6f/Peddler.jpg/200px-Peddler.jpg",
	}
];
